name: web_browser
version: 0.3.0
description: Widgets for showing web pages and web content. Uses webview_flutter in Android/iOS and
  iframe in browsers.
homepage: https://github.com/dint-dev/web_browser

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  meta: ^1.2.4
  share: ^0.6.5+4
  universal_html: ^1.2.4
  webview_flutter: '>=0.3.24 <=2.0.0'

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2