name: web_browser
version: 0.3.2
description:
  Widgets for showing web content. Uses webview_flutter in Android/iOS and HTML nodes in browsers.
homepage: https://github.com/dint-dev/web_browser

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: '>=0.1.3 <2.0.0'
  flutter:
    sdk: flutter
  meta: ^1.2.0
  share: ^0.6.0
  universal_html: ^1.2.3
  webview_flutter: '>=0.3.24 <2.0.0'

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2