name: web_browser
version: 0.4.0
description:
  A cross-platform Flutter widget for displaying websites and other web content. Has optional
  navigation buttons.
homepage: https://github.com/dint-dev/web_browser

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: '>=0.1.3 <2.0.0'
  flutter:
    sdk: flutter
  meta: ^1.2.0
  share: ^0.6.0
  universal_html: ^1.2.3
  web_node: ^0.1.1
  webview_flutter: '>=0.3.24 <2.0.0'

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2